### ISSUE TITLE
Collection API Feature Request

### ISSUE THREAD

**Issue by daplcor** [CryptoPascal31/marmalade-ng#2]
The Collection Policy is well-written and documented.  However, it would also be nice to track a collection's creator.  This allows marketplaces or wallets to quickly identify groupings of collections, perform lookups, and help with self-minting capabilities.

Recommended:
Add creator:string to the schema

During create-collection require this field

Local lookup to return a list of collections that belong to the creator.

**Comment by CryptoPascal31** [comment]
Addressed by https://github.com/CryptoPascal31/marmalade-ng/pull/3
